// flow-typed signature: 824e88195ae052092164d1ae25ac5d37
// flow-typed version: <<STUB>>/emoticons_v0.1.8/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoticons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoticons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoticons/lib/emoticons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoticons/lib/emoticons.js' {
  declare module.exports: $Exports<'emoticons/lib/emoticons'>;
}
